resources:
  - name: dhall_templates_gitRepo
    type: GitRepo
    configuration:
      path: shimib/selfserviceportalautomation
      gitProvider: shimiz
      buildOn:
        commit: true
  - name: execution_webhook
    type: IncomingWebhook
    configuration:
            webhookName: triggerSelfServiceAutomation
pipelines:
  - name: onboard_project
    steps:
    - name: generateTemplatesAndExecute
      type: Bash
      configuration:
       environmentVariables:
            TEAM: '${team}'
            MATURITIES: '${maturities}'
            PACKAGES: '${packages}'
       inputResources:
        - name: dhall_templates_gitRepo
          trigger: false
        - name: execution_webhook
       integrations:
        - name: ArtifactoryUnified
      execution:
       onStart:
        - "wget https://github.com/dhall-lang/dhall-haskell/releases/download/1.31.1/dhall-1.31.1-x86_64-linux.tar.bz2"
        - "tar -xvf dhall-1.31.1-x86_64-linux.tar.bz2"
        - "export PATH=${PATH}:${PWD}/bin"
        - "cd ${res_dhall_templates_gitRepo_resourcePath}/src"
        - export TEAM=`echo ${res_execution_webhook_payload} | jq -r '.team'`
        - echo $TEAM
        - export PACKAGES=`echo "${res_execution_webhook_payload}" | jq -c '.packages' | tr '[:upper:]' '[:lower:]' | sed  -E "s/\"([a-z]+)\"/PackageType\.\1/g"`
        - echo $PACKAGES
        - sed -i -E "s/^(.+packages = ).+$/\1${PACKAGES}/"  ./Policy/Env.dhall
        - "cat ./Policy/Env.dhall"
        - retry_command jfrog rt config --url $int_ArtifactoryUnified_url --user
          $int_ArtifactoryUnified_user --apikey $int_ArtifactoryUnified_apikey
          --interactive=false
        - "./scripts/create_repos.sh $TEAM"
        - "cat 2*/*"
