resources:
  - name: dhall_templates_gitRepo
    type: GitRepo
    configuration:
      path: shimib/selfserviceportalautomation
      gitProvider: shimiz
      buildOn:
        commit: false
  - name: execution_webhook
    type: IncomingWebhook
    configuration:
            webhookName: triggerSelfServiceAutomation
pipelines:
  - name: onboard_project
    steps:
    - name: generateTemplatesAndExecute
      type: Bash
      configuration:
       environmentVariables:
            TEAM: '${team}'
            MATURITIES: '${maturities}'
            PACKAGES: '${packages}'
       inputResources:
        - name: dhall_templates_gitRepo
          trigger: false
        - name: execution_webhook
      execution:
       onStart:
        - "cd ${res_dhall_templates_gitRepo_resourcePath}/src"
        - "echo echo into then Env.dhall"
        - "cat ./Policy/Env.dhall"
        - "./scripts/create_repos.sh --dry-run"
