resources:
  - name: dhall_templates_gitRepo
    type: GitRepo
    configuration:
      path: shimib/selfserviceportalautomation
      gitProvider: shimiz
      buildOn:
        commit: false
  - name: execution_webhook
    type: IncomingWebhook
    configuration:
            webhookName: triggerSelfServiceAutomation
pipelines:
  - name: onboard_project
    steps:
    - name: generateTemplatesAndExecute
      type: Bash
      configuration:
       environmentVariables:
            TEAM: '${team}'
            MATURITIES: '${maturities}'
            PACKAGES: '${packages}'
       inputResources:
        - name: dhall_templates_gitRepo
          trigger: false
        - name: execution_webhook
      execution:
       onStart:
        - "wget https://github.com/dhall-lang/dhall-haskell/releases/download/1.31.1/dhall-1.31.1-x86_64-linux.tar.bz2"
        - "tar -xvf dhall-1.31.1-x86_64-linux.tar.bz2"
        - "export PATH=${PATH}:${PWD}/bin"
        - "cd ${res_dhall_templates_gitRepo_resourcePath}/src"
        - export TEAM=`"$res_execution_webhook_payload" | jq '.team'`
        - echo $TEAM
        - "cat ./Policy/Env.dhall"
        - "./scripts/create_repos.sh --dry-run"
